# Ensure kernel modules are configured

---

- name: Ensure kernel modules are loaded
  community.general.modprobe:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  become: true
  loop: '{{ fedora_kernel_modules }}'

- name: Ensure kernel modules are configured
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    mode: 0644
    create: true
  become: true
  loop: '{{ fedora_kernel_modules }}'
