# Ensure packages are configured

---

- name: Ensure packages are upgraded
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: fedora_upgrade_packages

- name: Ensure packages are configured
  ansible.builtin.dnf:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    autoremove: '{{ true if item.state | default("present") == "absent" else false }}'
  become: true
  loop: '{{ fedora_packages }}'
